---
java/jre-1.6.0_24-x86_64.tar.gz:
  object_id: 1f403bc7-0cc4-4638-b777-0eeb916837ac
  sha: !binary |-
    MDUxMWQ4MzNkZmQ5ODI1YTI2YzE4ZTlkNjg1ZGU2NGFjMDE1MWU4NQ==
  size: 34453414
jenkins/jenkins-1.509.2.war:
  object_id: a8234a26-eaaa-4134-8db7-c80e0d300bbf
  sha: !binary |-
    N2Q1OTVkZGQ4NTdmOTk5Yjc3MGIwZWMwMmI5YjBlODhjMGIyZTE3YQ==
  size: 53863401
